import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextFont, NextFontWithVariable } from "next/dist/compiled/@next/font";

const montserrat: NextFont = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Euler Cortes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={montserrat.className} lang="en">
      <body className="relative h-screen bg-[#121212]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
